const JOIN_ROOM = "JOIN_ROOM";
const MESSAGE_ROOM = "MESSAGE_ROOM";

const ROOM_DATA = "ROOM_DATA";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const ROOM_JOIN_ALERT = "ROOM_JOIN_ALERT";

const VIDEO_PAUSE = "VIDEO_PAUSE";
const VIDEO_PLAY = "VIDEO_PLAY";
const VIDEO_SYNC = "VIDEO_SYNC";
const SEEK_TO = "SEEK_TO";

export {
  JOIN_ROOM,
  MESSAGE_ROOM,
  ROOM_DATA,
  NEW_MESSAGE_ALERT,
  VIDEO_PAUSE,
  VIDEO_PLAY,
  VIDEO_SYNC,
  ROOM_JOIN_ALERT,
  SEEK_TO,
};
