const JOIN_ROOM = "JOIN_ROOM";
const MESSAGE_ROOM = "MESSAGE_ROOM";

const ROOM_DATA = "ROOM_DATA";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const VIDEO_PAUSE = "VIDEO_PAUSE";
const VIDEO_PLAY = "VIDEO_PLAY";
const VIDEO_SYNC = "VIDEO_SYNC";

module.exports = {
  JOIN_ROOM,
  MESSAGE_ROOM,
  ROOM_DATA,
  NEW_MESSAGE_ALERT,
  VIDEO_PAUSE,
  VIDEO_PLAY,
  VIDEO_SYNC,
};
